---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-gin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-gin
  template:
    metadata:
      labels:
        app: hello-gin
    spec:
      enableServiceLinks: false
      imagePullSecrets:
        - name: imgcred
      containers:
        - name: hello-gin
          image: harbor.codemowers.eu/ingermhelena/hello-gin@sha256:69286a073cadd205097ee970ae29406c37dcb838a7f14bae51f4020a5817c6a9
          env:
            - name: USERNAME
              value: {{ .Values.username }}
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 8080
              name: metrics