---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-gin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-gin
  template:
    metadata:
      labels:
        app: hello-gin
    spec:
      enableServiceLinks: false
      imagePullSecrets:
        - name: imgcred
      containers:
        - name: hello-gin
          image: harbor.codemowers.eu/ingermhelena/hello-gin@sha256:b6b952d46fb434ea3c59137f39dd0992f71144d967b4e142be9ae17e4fbe38a5
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 8080
              name: metrics